--- # pjchat config
domain: "root.dects.dec112.eu"
user: "21223aeeb829ed8e611ffa2c8e95eb16"
passwd: "52b524e67250a7183a720bd5"
proxy: "sip:root.dects.dec112.eu;transport=tcp"
device: "39fa95fe-f0cc-a2b4-7c8c-91d876496342"
lon: "16.363449"
lat: "48.210033"
rad: "10"
ref: "http://root.dects.dec112.eu/api/v2/"
did: "did:ion:GTmRFQ2PhHIEgZzeUtA_u4j7cWiKDNaC3sBOwrldxqXoy5"
rid: "39fa95fe-f0cc-a2b4-7c8c-91d876496342"
api: "api-key"
eval: "(1) This is the (Echo Bot Service) of (DECTS (TEST))."
debug: "3" 
